# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0176a234a661cb4860a437464fdb0d93df181134883abcf6e7011abb98ab9fa1248e46fdac0efcd09aa6233be74afe91fb5474cafde97a1190f7441b608aa968

test:
  secret_key_base: d2d39811889cc3c25f4c4025a67797c4d170a8593a65c03395f571f1a9ec378dfdf89c9bb89dc9fd29debc00346f9dbf704a679bfe419f79708987ba244ae915

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
